- dr_flac.h
These few changes make it easier to embed the header into a C++ project by fixing some compile issues reported by C++ compilers.  Tested with clang.
> Make dr_flac.h compile with C++ compiler

- dr_flac.h
I'm not sure if this was intentional or not, but drflac_close doesn't actually free the structure.  Since drflac_open allocates it, it seems intuitive to me that drflac_close should free it again.
> free pFlac in drflac_close

- dr_flac.h
In various locations the code was returning false from a function that returns a pointer.  This is a compile error in emscripten.  This changes them to return NULL instead.
> return NULL on error from functions that return pointer

- dr_flac.h
This fixes a compilation issue in gcc versions before 4.3 caused by a copy&paste error in a preprocessor comparison.
> Fix version check for pre-gcc 4.3

- dr_wav.h
Thanks a lot for the lib, it's very easy to use.
I used dr_wav to parse wav audio, and got a DR_FALSE when wav file had JUNK chunk.
I tried to ignore the JUNK chunk if existed, and it worked. Please review if this is proper.
> ignore JUNK chunk in wave header

- dr_flac.h
Fixed a number of "initialization from incompatible pointer type" warnings.
Tested working on the 3DS with 16bit Stereo Flac files.
Signed-off-by: Mahyar Koshkouei <deltabeard@users.noreply.github.com>
> dr_flac: Fix init from incompatible pointer type

- dr_flac.h
Fixed an issue whereby if DR_FLAC_NO_SIMD was not defined and the target
architecture was not x86 or x64, CPUID was not disabled.
The compile error was:
"implicit declaration of function 'drflac__cpuid';"
despite compiling for an armv6 architecture.
Tested working on a 3DS.
Signed-off-by: Mahyar Koshkouei <mk@deltabeard.com>
> Stop CPUID on unsupported architectures

- dr_flac.h
Fixed the warning "'drflac__gIsSSE42Supported' defined but not used"
when compiling for a system that does not support currently implemented
CPU optimisations. This warning may cause projects to not compile.
Tested working on a 3DS.
Signed-off-by: Mahyar Koshkouei <mk@deltabeard.com>
> Fix unused definition warning

- dr_flac.h
- dr_math.h
- dr_obj.h
- dr_wav.h
Allow user to specify the file size up-front for `.wav` file write functions, to allow fully sequential writing to the file. User should set the `totalNumSamples` parameter to 0 to use the prior behavior, where file size is unknown ahead of time.
NEEDS REVIEW! I added the parameter to all the wav file write functions, but only tested it with `drwav_init_file_write()`, `drwav_write()`, and `drwav_uninit()`.
I am creating some `.wav` files with MD5 sums. I am calculating the MD5 sums on-the-fly. The seek back to correct the chunk sizes in `drwav_uninit()` precludes this behavior.
Purely sequential writing is preferable for flash media, too.
- In this implementation, if you specify a file size (non-zero `totalNumSamples`) on file write init, then:
- The `onSeek` function is not required. If …
> sequential write

- dr_wav.h
I added a couple of utility functions for computing the total size of a target, based on provided metadata. Is the algorithm correct?
I'm working with a file system where I have to know the file size in order to create the file. That makes this a useful feature.
It looks to me like dr_wav supports reading from more types of files than it supports writing to (e.g. files w/ smpl loops), so I put `write` in the function names, to indicate it's only for that purpose.
> dr_wav: utility functions for computing total target write size

- dr_flac.h
- dr_wav.h
- wip/dr_opus.h
Compiling dr_wav and dr_flac with Visual Studio .NET 2003 gives me errors about `_byteswap_ushort` not being found. It'd be nice if Microsoft's docs pointed out when that was added, but a quick search turned up nothing.
> MSVC2003 doesn't seem to have byte swap intrinsics

- dr_mp3.h
This is related to #125.
cfc9a39178e6f2349ce28ca5c09a93217b680957 seems to be the commit that caused the bug, rather than what fixed it.
> dr_mp3: Fix error with `DR_MP3_NO_STDIO`

- dr_flac.h
Comparison is always true, because code above returns early when
unsigned blockSize is 0. This invariant is asserted just before
if-else chain.
---
This is a follow up to #176 - to present an alternative fix. I also experimented with replacing these if-else's with a switch statement, but replacing this single comparison with an assert is less invasive change, and more readable.
> dr_flac: Remove comparison that is always true

- .gitignore
- tests/README.md
- tests/build_flac_linux.sh
Fixes:
```
/tmp/ccLFJs1C.o: In function `dr_dlopen':
dr_flac_test_0.c:(.text+0x1d1f6): undefined reference to `dlopen'
/tmp/ccLFJs1C.o: In function `dr_dlclose':
dr_flac_test_0.c:(.text+0x1d201): undefined reference to `dlclose'
/tmp/ccLFJs1C.o: In function `dr_dlsym':
dr_flac_test_0.c:(.text+0x1d211): undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
```
build_flac_linux changed to follow documentation and linux convention.
Info on testing flac added to README.md.
> dr_flac: tests - build_flac_linux fix and improvement. Add flac tests to README.md

- LICENSE
This simply extracts the copyright and license statement that is in the footer of each of the `dr_*.h` files to a separate file.
This is helpful when packaging for certain Linux distributions, but I think it would be useful to other users as well.
> Add a separate LICENSE file

- tests/wav/dr_wav_common.c
This will usually allow the tests to work with a system-wide installation of libsndfile without further fuss.
> Also try dlopen’ing libsndfile.so.1, which will often work on Linux

- dr_mp3.h
Fixes build failure on ARMv6 (https://github.com/mackron/dr_libs/issues/193).
> Change int32_t to drmp3_int32 in dr_mp3.h. Fixes #193.

- dr_flac.h
- dr_mp3.h
dr_flac.h(11543): Warning! W124: Comparison result always 0
dr_flac.h(11544): Warning! W124: Comparison result always 0
dr_flac.h(11545): Warning! W124: Comparison result always 0
dr_mp3.h(4190): Warning! W124: Comparison result always 0
dr_mp3.h(4257): Warning! W124: Comparison result always 0
> silence annoying watcom warnings:

- dr_mp3.h
This patch allows overriding memcpy, memset and memmove easier.
Without this, we hit an issue in SDL_sound with MSVC 2015, see:
https://github.com/icculus/SDL_sound/issues/25
> replace direct uses of memset, memcpy and memmove by DRMP3_* macros

- dr_flac.h
The seektable of some `.flac` files might start with a pcm frame greater then 0. Therefore a requested `pcmFrameIndex` could be from before the beginning of the seektable. This in turn confuses the computation of `byteRangeLo` and `byteRangeHigh` down the road.
This is a simple fix of the issue by early returning from `drflac__seek_to_pcm_frame__seek_table(...)` to fall back to the next available seek method. I guess the best would be to always fall back to the brute force method, right?
> dr_flac: Do not use the seektable if pcmFramIndex is not coverd by it.

- dr_flac.h
Using an emscripten debug build with `-s SAFE_HEAP=1` https://emscripten.org/docs/porting/Debugging.html#compiler-settings it got an alignment fault on https://github.com/mackron/dr_libs/blob/c5e53558165585ae624a7d6c7908e698609093c8/dr_flac.h#L6514 when calling `drflac_open_with_metadata`.
Looking at the spec for `METADATA_BLOCK_VORBIS_COMMENT`, it appears there aren't any alignment requirements, so the `uint32`'s may not be 4 byte aligned. This may need to be also be fixed in other metadata blocks.
This PR adds a function to read a little endian 32 bit integer from a potentially unaligned ptr and replaces the uint32 reading for `METADATA_BLOCK_VORBIS_COMMENT` with it. This fix should work on big and little endian.
Edit: Also added fix to `drflac_next_vorbis_comment` as I ran into the …
> dr_flac: remove unaligned 32 bit loads when parsing vorbis comments

- dr_flac.h
- tests/flac/fuzz_dr_flac.c
The first commit (41c6caf) of this PR adds a fuzzer to the FLAC tests, which can be build exclusively with clang. It is inspired by (though is not a derivative of) the libFLAC fuzzer. When combined with -fsanitize options it is able to find bugs that can potentially cause security issues.
Commit c51ad32 silences certain (IMO benign) warnings generated when fuzzing with -fsanitize=undefined, the other 5 commits fix various problems found with the fuzzer. I have ran the test program on a set of testvectors with and without these patches on my Raspberry Pi 4 (ARM64) machine, and there seems to be no measureable impact of these patches combined together on decoding speed.
The second of the commits (04552a5), is in my view the most important, because it caused dr_flac to run extremely slow …
> Add FLAC fuzzer and fix found bugs

- dr_mp3.h
Hi David,
I ran the code through PVS Studio static code analyzer and fixed a couple of minor complaints where it wanted some of the variables in macros surrounded by parentheses.
> Fix small macro nits found by PVS studio.

- dr_flac.h
The code on `drflac_has_sse41` seems to be copy pasted from `drflac_has_sse2` and as such I think the detection has some problems. 
```cpp
#if defined(DRFLAC_X64)
return DRFLAC_TRUE;    /* 64-bit targets always support SSE4.1. */
```
True for SSE2, not necessarily true for SSE4.1
```cpp
#elif (defined(_M_IX86_FP) && _M_IX86_FP == 2) || defined(__SSE4_1__)
```
`_M_IX86_FP == 2` is true when using `/arch:SSE2` with MSVC but also doesn't seem to define the SSEn macros, yet it does define AVX. 
This code is untested, cuz I'm lazy as I've been using `DRFLAC_NO_SSE41` as a workaround.
> dr_flac: Avoid illegal instruction on old systems.

- dr_flac.h
Some compilers do report the absence of initialisation here as a possible use of uninitialized value.
> dr_flac.h: Fixed a "use of uninitializated value" warning

- tests/flac/dr_flac_common.c
This check should be for pStreamDecoder instead of pDecoder
> fix: This check should be for pStreamDecoder instead of pDecoder

- dr_mp3.h
This change is useful, if you want to extract the introductory paragraph from dr_{mp3,flac,wav}.h via regular expressions like it's done [here](https://github.com/gentoo/guru/commit/b88d3ed0965aeae7ff98e453e6216e92eaea2f3c#r134692400).
> dr_mp3.h: Fix typo in comment, 'Introducation' -> 'Introduction'

- .gitmodules
If a repo includes dr_libs as a submodule, a recursive clone would also pull miniaudio with its full history, which currently takes up 157.5 MiB on disk. Declaring miniaudio as shallow would reduce this to 7.4 MiB by only downloading any data needed for the recorded commit. This seems to be a better default for consumers who most likely won't need to jump around in miniaudio's history, if they even build the tests at all. This won't affect existing checkouts, and even new ones can later add back the history via `git fetch --unshallow`.
> Declare the miniaudio submodule as shallow

- dr_flac.h
- dr_mp3.h
- dr_wav.h
We use dr_libs as a part of [https://github.com/microsoft/onnxruntime-extensions](https://github.com/microsoft/onnxruntime-extensions) and observe compilation error.
This PR is having two fixed for compilation error found in AIX OS.
- 
```
In file included from /ranjit/onnxruntime-genai/build/AIX/Release/_deps/onnxruntime_extensions-src/operators/audio/audio_decoder.cc:11:
/ranjit/onnxruntime-genai/build/AIX/Release/_deps/dr_libs-src/dr_flac.h: In function 'drflac_result drflac_result_from_errno(int)':
/ranjit/onnxruntime-genai/build/AIX/Release/_deps/dr_libs-src/dr_flac.h:8298:9: error: duplicate case value
8298 |         case ENOTEMPTY: return DRFLAC_DIRECTORY_NOT_EMPTY;
|         ^~~~
/ranjit/onnxruntime-genai/build/AIX/Release/_deps/dr_libs-src/dr_flac.h:8232:9: note: previously used …
```
> [AIX] Fixing the compilation issue for AIX OS

- dr_wav.h
As per discussion in #267, I've just renamed the fields. This will cause breakages to users that can reevaluate their codebase wrt those fields.
Fixes #267
> Fix fields holding smpl/cue offsets as they are in samples not bytes

- dr_mp3.h
drmp3_calculate_seek_points() builds the table with file positions like this:
```c
mp3FrameInfo[iMP3Frame].bytePos = pMP3->streamCursor - pMP3->dataSize;
```
drmp3_decode_next_frame_ex__callbacks() updates both streamCursor and dataSize, but drmp3_decode_next_frame_ex__memory() does not, so all entries in the seek table end up pointing at the start of the audio file.
This patch updates streamCursor as we read more bytes, but leaves dataSize at zero, since the latter appears to be how much is left to consume of the existing read buffer before more is read from disk, so subtracting zero in drmp3_calculate_seek_points() is the correct thing to do when reading entirely from memory.
Fixes #278.
> dr_mp3: Fix seek table generation with memory buffers instead of i/o callbacks.

- dr_wav.h
on line 2531 the reader consumes one byte too much (extraBytes + 1). This can cause a DRWAV_ASSERT.
This fix adds the missing byte to the extraCapacity in stage 1.
> bext size allocation error

- dr_wav.h
Adds support for `location`, `organization`, `keywords`, `medium` and `description` metadata list info tags in WAV.
This expands the amount of supported list infos from 9 to 14. Normally [there should be support for 23](https://www.recordingblogs.com/wiki/list-chunk-of-a-wave-file) (ITRK is already supported but not listed there), but I don't think the missing ones are that important.
> WAV: Add support for a few more list info metadata

- dr_vorbis.h
My editor strips trailing spaces, so this pr is a little noisy.
When vorbis included in a cpp file and `DR_VORBIS_NO_STDIO` is defined, this would fail to build because of the open functions returning an errno (int) to dr_vorbis_result (enum). I changed this to return the result directly. I figuired IO error was a more fitting return result.
I also made the crc32 table const.
> vorbis: fix return code when stdio is disabled, make static crc32 table const.
